### ISSUE TITLE
positional embedding

### ISSUE THREAD

**Issue by lucidrains** [lucidrains/charformer-pytorch#1]
![Screenshot from 2021-06-30 12-12-17](https://user-images.githubusercontent.com/108653/124018202-70787480-d99c-11eb-8826-7f2914aa7c5c.png)

in section 2.1.1 in the paper, the authors claim that by adding intra-block positional embeddings https://github.com/lucidrains/charformer-pytorch/blob/main/charformer_pytorch/charformer_pytorch.py#L90-L96 the block representations will be aware of the position of each character. however, if one were to be doing mean pooling as the author propose, wouldn't this amount to just adding the mean of the positional embeddings for every block? If anyone has any insights, please leave a comment

**Comment by machineko** [comment]
I think it would be the same operation i tested it with simple script in simple jupyter and indeed it looks the same.
But I'm not sure if i understood this calculation properly 😄 

![image](https://user-images.githubusercontent.com/42299606/124038676-ce8b7300-da01-11eb-9fa8-0f0c652e986d.png)

**Comment by lucidrains** [comment]
yea, i don't think it would let the network know which character was in which position within a block, so i'm confused

**Comment by lucidrains** [comment]
![Screen_Shot_2021-07-07_at_6 45 35_PM](https://user-images.githubusercontent.com/108653/124857290-e3678980-df60-11eb-8186-d2fa23b40096.png)

in v2 of the paper, they mention using a conv, so i made that change in 0.0.3
