### ISSUE TITLE
Cannot tokenize on GPU

### ISSUE THREAD

**Issue by Shamepoo** [lucidrains/charformer-pytorch#2]
Hi,

I'm using Charformer to do some error corrections on Colab. But I found that after I pass tokens to CUDA and start tokenizing, this would show up:
![image](https://user-images.githubusercontent.com/49515860/124345062-f4cf2f80-dc08-11eb-91d4-e7738ae4c3a6.png)

Did I do it in a wrong way?

**Comment by lucidrains** [comment]
@Shamepoo ohh, you'll need to do `tokenizer = tokenizer.cuda()` as well!

**Comment by Shamepoo** [comment]
> @Shamepoo ohh, you'll need to do `tokenizer = tokenizer.cuda()` as well!

Thank you!!
